# -*- mode: ruby -*-
# vi: set ft=ruby :
 
Vagrant::Config.run do |config|
# Use 32-bit Ubuntu to get up and running
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
# Cannot get Java install run by the oab-java.sh setup script to work on 64 bit yet
#  config.vm.box = "precise64"
#  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
#  config.vm.box_url = "http://cloud-images.ubuntu.com/quantal/current/quantal-server-cloudimg-vagrant-amd64-disk1.box"

  config.vm.forward_port 8080, 8080  

  config.vm.provision :shell, :inline => "apt-get update"
  # Otherwise java install will fail with missing dependencies
  
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "chef/cookbooks"
    chef.add_recipe "tomcat7"
  end
end
